### ISSUE TITLE
When used with gamm4, error in eval: object not found (v. 2.3-0)

### ISSUE THREAD

**Issue by klabarb** [pbreheny/visreg#25]
I think this is the same issue from issue #19 , but I am using the most recent version (2.3-0). I'm in R v. 3.3.2 for Mac.

My code (not reproducible):

> m1 <- gamm4(Wing ~ s(Age) + Hatchdate + Paternity, random = ~ (1|Nest/Chick), data = growth)
> visreg(m1$gam, by = "Paternity", data = growth)
Error in eval(expr, envir, enclos) : object 'Wing' not found

Would very much appreciate any help because this is the only package I've found that would make the plot I need!

**Comment by pbreheny** [comment]
Hard to tell with non-reproducible code, but the first thing I would do is to tell visreg what you want on the x axis:

> visreg(m1$gam, "Age", by = "Paternity", data = growth)

Second, are all the variables actually contained in `growth`?  Or are some in `growth` and others in the global environment?

**Comment by klabarb** [comment]
In the course of constructing reproducible code to demonstrate the problem, I got it working! Hurray! Sorry to have bothered you. The problem seems to be related to where/how the dataset was loaded - I imported it using read.table, which works fine for the gamm functions, but I guess visreg couldn't find it? But attach(growth) fixed everything.

**Comment by pbreheny** [comment]
Actually, looking into this a little more, I can now see what the issue is.  Generally, when you fit a model, the call is returned so that visreg can see what the name of the data object is (try typing in `fit$call` for an lm/glm/gam/etc. fit).  That doesn't happen with gamm4, however: `fit$call` returns NULL; essentially, gamm4 isn't telling visreg where to find the data.  I would describe this more as a gamm4 issue than a visreg issue, but another way to work around it is to store a copy of the data in fit$gam.  Here's a reproducible example:

```r
x <- runif(100)
fac <- factor(sample(1:20,100,replace=TRUE))
eta <- x^2*3 + as.numeric(fac)/20
y <- rpois(100,exp(eta))
Data <- data.frame(x=x, y=y, fac=fac)
rm(x)
rm(y)
rm(fac)
fit <- gamm4(y~s(x),family=poisson,random=~(1|fac), data=Data)

# Doesn't work; can't find Data
visreg(fit$gam, "x")
fit$gam$call

# This works
fit$gam$data <- Data
visreg(fit$gam, "x")
```

**Comment by klabarb** [comment]
Ah, that all makes sense. Good to know that this happens, since I use gamm4 a lot - I'll keep an eye out for related issues when I use it now. Thank you!
(And I made some lovely figures with visreg, so thank you for that too!)
