### ISSUE TITLE
visreg plot based on poisson glm changes into a rug plot when using scale = "response"

### ISSUE THREAD

**Issue by cmartin** [pbreheny/visreg#55]
It seems like there is some issue with visreg when plotting from GLMs.

On the linear scale, the plot is correct (with points etc.), but when using the reponse scale, it gets turned into a rug plot unless explicitly instructed to create a partial plot.

```r
library(visreg)
n <- 100
x1 <-  runif(n)
d <- data.frame(
  x1 = x1,
  y = rpois(n,x1)
)

m2 <- glm(y~x1, family = "poisson", data = d)

par(mfrow=c(1,3))
visreg(m2,"x1", scale = "linear")
visreg(m2,"x1", scale = "response")
visreg(m2,"x1", scale = "response", partial = TRUE)
par(mfrow=c(1,1))
```

**Comment by pbreheny** [comment]
This is intentional. The issue is that partial residuals are calculated and are meaningful on the scale of linear predictors. Once you transform them, I really can't guarantee that they have any meaning. Because they are potentially misleading, they are explicitly turned off in visreg when you transform the response.

You can read more about it [here](#1) and [here](#51) if you would like.

**Comment by cmartin** [comment]
Thanks for the quick response. Please note that the links in your previous comment don't seem to point to the right place (relative links into this issue (#55)? )

This link might be of interest to those struggling with this issue : http://pbreheny.github.io/visreg/glm.html

I still feel it is awkward to have a rug plot associated with a poisson response (I never saw it for anything beside proportions before), but I get your point about the magnitude of the residuals.

**Comment by pbreheny** [comment]
Oops, sorry, fixed the broken link issue by editing my comment above.  In my opinion, there's not a perfect answer to this question that works in all cases.  I don't forbid people from plotting transformed partial residuals when `scale="response"`, it's just that I want people to think about it and be aware of the issues, so that's why it's not turned on by default.
