### ISSUE TITLE
color points by group

### ISSUE THREAD

**Issue by DemaLM** [pbreheny/visreg#56]
Hi, 

I'd like to have specific colors for groups in my points in the visreg output.

So for instance, taking the mixed model example:
```
library(lme4)
data(Milk, package="nlme")
fit <- lmer(protein ~ Diet + Time + (Time|Cow), Milk)
visreg(fit, "TIme", ylab="Protein", gg=TRUE)
 theme_bw()+
      geom_point(size=3, alpha=0.1,group="Diet", shape=16)
```
![image](https://user-images.githubusercontent.com/19428346/42950897-e7ba531e-8b6c-11e8-90eb-501f634c47ce.png)

In this case, I don't know why are there dots in the middle of the points. Just can't remove them. 
Second, I'd color the points with specific colors for Diet using ggplot as above .

Many thanks!

**Comment by pbreheny** [comment]
1. The points are added by the call to visreg.  You're adding the gray circles with `geom_point`.  If you don't want `visreg` to plot the partial residuals, the option is `partial=FALSE`.  So, for example:

```r
visreg(fit, "Time", ylab="Protein", gg=TRUE, partial=FALSE, rug=FALSE) +
  theme_bw() +
  geom_point(size=3, alpha=0.1, shape=16)
```

2. Colors can be added with the `by` and `overlay` arguments:

```r
visreg(fit, "Time", ylab="Protein", gg=TRUE, by="Diet", overlay=TRUE)
```
![a](https://user-images.githubusercontent.com/1858089/42961780-70bb14ea-8b55-11e8-9a17-7a6801c65357.png)


3. If you want to turn off `visreg`'s plotting of points and plot them yourself, you can, but (a) this would need to be done through the `aes` interface in `ggplot2` and (b) you still need to set up a `by` variable, otherwise it won't be included in the data frame that `ggplot2` is based on:

```r
visreg(fit, "Time", ylab="Protein", gg=TRUE, by="Diet", overlay=TRUE, partial=FALSE, rug=FALSE) +
  theme_bw() +
  geom_point(aes(color=Diet), size=3, alpha=0.1, shape=16)
```
![b](https://user-images.githubusercontent.com/1858089/42961785-7391a72e-8b55-11e8-84d5-e19c05191406.png)

4. As of commit 4d74360, you can also just pass the graphical parameters to `visreg` via `points.par`:

```r
visreg(fit, "Time", ylab="Protein", gg=TRUE, by="Diet", overlay=TRUE,
       points.par=list(size=3, alpha=0.1), jitter=TRUE)
```
![c](https://user-images.githubusercontent.com/1858089/42961993-1df15fa2-8b56-11e8-97ff-5dea5c5408bf.png)

**Comment by DemaLM** [comment]
Thank you very much for your help!
One last thing:  I understood your last two examples to use Diet to color the points, however, is it possible to use a variable which is not specified in the model to color the points? 
For example, if there were a "Farm.ID" variable in the Milk dataset and I'd like to use it as a grouping variable to color the points according to this variable. 

Thanks

**Comment by pbreheny** [comment]
You can do it, although you would have to manually add the variable to the visreg object; otherwise, if the variable isn't in the model frame, `visreg` doesn't have access to it.  For example:

```r
fit <- lmer(protein ~ Time + (Time|Cow), Milk)
v <- visreg(fit, "Time", ylab="Protein", jitter=TRUE, plot=FALSE)
v$res$Diet <- Milk$Diet
png('d.png', width=450, height=360)
plot(v, gg=TRUE, partial=FALSE, rug=FALSE) + theme_bw() +
  geom_point(data=v$res, aes(x=Time, y=visregRes, color=Diet), size=3, alpha=0.1, shape=16)
dev.off()
```
![d](https://user-images.githubusercontent.com/1858089/43105423-72febba6-8e9a-11e8-8fba-b0356cd4cb49.png)

**Comment by DemaLM** [comment]
That's exactly what I wanted! 
Thank you very much!!!

**Comment by sportModel** [comment]
Happy to help!

**Comment by pbreheny** [comment]
Happy to help!
