### ISSUE TITLE
partial residuals based on deviance residuals

### ISSUE THREAD

**Issue by robjhyndman** [pbreheny/visreg#57]
For GLMs, you compute partial residuals based on deviance residuals in `visreg:::visregResid()`. I'm not sure this makes sense. All the references I can find on partial residuals for GLMs define them using residuals divided by their variances (not standard deviations as in Pearson residuals). See, for example, Section 5 of Landwehr et al (JASA 1984, http://doi.org/10.1080/01621459.1984.10477062). 

Other R packages also seem to do it this way (e.g., car)

Is there some theoretical justification for your deviance-based partial residuals? If not, would you consider changing to the conventional definition? (It would make my teaching a lot simpler!)

**Comment by pbreheny** [comment]
In my opinion, deviance residuals are much better for visualizing GLMs than other types of residuals because they are symmetric; see #27 for a specific example in which I argue that the deviance-based construction is very useful and the standard construction misleading if not useless.  I'm open to arguments to the contrary, but I think deviance residuals much better for the types of plots visreg constructs.

That said, I have had several requests for a feature allowing you to pass options to the residuals method and thereby choose other types of residuals if you want them.  I'd like to do that, but haven't gotten around to it.
